### ISSUE TITLE
How to play song in our react native app?

### ISSUE THREAD

**Issue by ganeshi8lab** [osamaq/spotify-lite#5]
I tried your apk, it's just searching and displaying song list.
How to play song in your app?
is it possible

**Comment by osamaqarem** [comment]
Unfortunately its not possible due to limitation from Spotify API/SDK!

https://developer.spotify.com/documentation/web-api/reference-beta/

https://developer.spotify.com/documentation/android/

https://developer.spotify.com/documentation/ios/#api-documentation

You can however make it function as a remote player for the real spotify app. I never properly finished up that part though 😅
